name = 'imghosting'
main = 'src/index.ts'
compatibility_date = '2024-12-01'
compatibility_flags = ['nodejs_compat']

[vars]
ENVIRONMENT = 'production'
R2_PUBLIC_URL = 'https://r2.prpr-bocchi.org'

# Images binding for image transformations
[images]
binding = "IMAGES"

# R2 Bucket binding
[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'imghosting'

# D1 Database binding
[[d1_databases]]
binding = 'DB'
database_name = 'imghosting'
database_id = "aa62cc93-cf20-49f5-b8f6-59455cec66f7"
